// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4a89hSq9AqZFIHFNMrR581ww_6ede7sY',
    appId: '1:311044293229:web:3795f5b0ae1e4afe207564',
    messagingSenderId: '311044293229',
    projectId: 'organ-donation-fbd9c',
    authDomain: 'organ-donation-fbd9c.firebaseapp.com',
    storageBucket: 'organ-donation-fbd9c.firebasestorage.app',
    measurementId: 'G-8M9BNXKT88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQjvwbemHESMw26KKxMq2cjAZwtPcM560',
    appId: '1:311044293229:android:958835a019a04908207564',
    messagingSenderId: '311044293229',
    projectId: 'organ-donation-fbd9c',
    storageBucket: 'organ-donation-fbd9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlZv8rNXtwdkJegIXaL2vSlF6z6DzRsK8',
    appId: '1:311044293229:ios:56489070ac4297cc207564',
    messagingSenderId: '311044293229',
    projectId: 'organ-donation-fbd9c',
    storageBucket: 'organ-donation-fbd9c.firebasestorage.app',
    iosBundleId: 'com.example.organDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlZv8rNXtwdkJegIXaL2vSlF6z6DzRsK8',
    appId: '1:311044293229:ios:56489070ac4297cc207564',
    messagingSenderId: '311044293229',
    projectId: 'organ-donation-fbd9c',
    storageBucket: 'organ-donation-fbd9c.firebasestorage.app',
    iosBundleId: 'com.example.organDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4a89hSq9AqZFIHFNMrR581ww_6ede7sY',
    appId: '1:311044293229:web:25ea1e214c1ce313207564',
    messagingSenderId: '311044293229',
    projectId: 'organ-donation-fbd9c',
    authDomain: 'organ-donation-fbd9c.firebaseapp.com',
    storageBucket: 'organ-donation-fbd9c.firebasestorage.app',
    measurementId: 'G-S3XZLZHWS4',
  );
}
